# Generated by Django 4.0 on 2023-03-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer',
            new_name='Broadband',
        ),
    ]
